### ISSUE TITLE
Generate typespecs

### ISSUE THREAD

**Issue by acalejos** [acalejos/flint#5]
Automatically generate typespecs from schema. Other libraries already do this, but preferably this could be done without extra dependencies

**Comment by fishtreesugar** [comment]
I think the ["Typed extension" with `typed_ecto_schema`](https://twitter.com/ac_alejos/status/1859366966664011908) implemented this feature. I can treat this library as a replacement of https://github.com/bitwalker/strukt finally 🎉

**Comment by acalejos** [comment]
@fishtreesugar You are correct, it was included in the latest release. I wasn't aware of that library, so glad Flint is filling a need for you!
